const conf = {
    APPWRITE_PROJECT_ID: String(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID),
    APPWRITE_API_KEY: String(process.env.NEXT_PUBLIC_APPWRITE_API_KEY),
    APPWRITE_DATABASE_ID: String(process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID),
    APPWRITE_COLLECTION_ID: String(process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ID),
}

export default conf;